// Configuration file for EEA Elasticsearch River Plugin
// check
// https://github.com/eea/eea.elasticsearch.river.rdf/blob/master/README.rst
// to see how the configration options work
// Please do not edit this file directly on production servers

// RDF endpoint to query
var path = require('path');

var endpoint = "http://cr.eionet.europa.eu/sparql";

fs = require("fs")

var queryTemplate = fs.readFileSync(path.join(__dirname,'queryTemplate.sparql'), 'utf8');
var filtersQuery = fs.readFileSync(path.join(__dirname,'filtersQuery.sparql'), 'utf8');

module.exports = {
    'endpoint': endpoint,
    'queryTemplate': queryTemplate,
    'filtersQuery': filtersQuery
};
