// Configuration file for EEA Elasticsearch River Plugin
// check
// https://github.com/eea/eea.elasticsearch.river.rdf/blob/master/README.rst
// to see how the configration options work
// Please do not edit this file directly on production servers

// RDF endpoint to query

var endpoint = "http://cr.eionet.europa.eu/sparql";
var queryType = "select";

var fields = [
    "http://reference.eionet.europa.eu/aq/ontology/aggregationType_link",
    "http://reference.eionet.europa.eu/aq/ontology/sample_inletHeight",
    "http://reference.eionet.europa.eu/aq/ontology/procedure_procedure",
    "http://reference.eionet.europa.eu/aq/ontology/sample_link",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneCountryLabel_link",
    "http://reference.eionet.europa.eu/aq/ontology/procedure_link",
    "http://reference.eionet.europa.eu/aq/ontology/datacapturePct_datacapture",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zone",
    "http://reference.eionet.europa.eu/aq/ontology/samplingpoint_lat",
    "http://reference.eionet.europa.eu/aq/ontology/station_link",
    "http://reference.eionet.europa.eu/aq/ontology/procedure",
    "http://reference.eionet.europa.eu/aq/ontology/beginPosition_year",
    "http://reference.eionet.europa.eu/aq/ontology/station_stationarea",
    "http://reference.eionet.europa.eu/aq/ontology/inserted",
    "http://reference.eionet.europa.eu/aq/ontology/station_geo_pos",
    "http://reference.eionet.europa.eu/aq/ontology/aggregationType_reportingmetric",
    "http://reference.eionet.europa.eu/aq/ontology/station_stationarea_link",
    "http://reference.eionet.europa.eu/aq/ontology/observationVerification",
    "http://reference.eionet.europa.eu/aq/ontology/station_lon",
    "http://reference.eionet.europa.eu/aq/ontology/endPosition",
    "http://reference.eionet.europa.eu/aq/ontology/sample",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneType",
    "http://reference.eionet.europa.eu/aq/ontology/station_lon_stationlongitude",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_stationtype",
    "http://reference.eionet.europa.eu/aq/ontology/sample_kerbdistance",
    "http://reference.eionet.europa.eu/aq/ontology/pollutant",
    "http://reference.eionet.europa.eu/aq/ontology/beginPosition",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_stationtype_link",
    "http://reference.eionet.europa.eu/aq/ontology/station_lat_stationlatitude",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zone_link",
    "http://reference.eionet.europa.eu/aq/ontology/procedure_analyticaltechnique",
    "http://reference.eionet.europa.eu/aq/ontology/procedure_measurementtype",
    "http://reference.eionet.europa.eu/aq/ontology/samplingpoint_lon",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneCountryLabel",
    "http://reference.eionet.europa.eu/aq/ontology/station_lat",
    "http://reference.eionet.europa.eu/aq/ontology/procedure_measurementtype_link",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_samplingPoint",
    "http://reference.eionet.europa.eu/aq/ontology/procedure_analyticaltechnique_link",
    "http://reference.eionet.europa.eu/aq/ontology/sample_sample",
    "http://reference.eionet.europa.eu/aq/ontology/unit",
    "http://reference.eionet.europa.eu/aq/ontology/updated",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint",
    "http://reference.eionet.europa.eu/aq/ontology/aggregationType",
    "http://reference.eionet.europa.eu/aq/ontology/station",
    "http://reference.eionet.europa.eu/aq/ontology/aggregationType_reportingmetric_link",
    "http://reference.eionet.europa.eu/aq/ontology/airqualityValue",
    "http://reference.eionet.europa.eu/aq/ontology/datacapturePct",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneLabel",
    "http://reference.eionet.europa.eu/aq/ontology/observationValidity",
    "http://reference.eionet.europa.eu/aq/ontology/airqualityValue_aqvalue",
    "http://reference.eionet.europa.eu/aq/ontology/inspireNamespace",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_link",
    "http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneType_link",
    "http://reference.eionet.europa.eu/aq/ontology/pollutant_link",
];

var queryTemplate_ =
"PREFIX dcterms: <http://purl.org/dc/terms/>\
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\
PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/>\
PREFIX aqdd: <http://dd.eionet.europa.eu/property/>\
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\
SELECT ?s ?p (if (bound(?isgeo), concat(str(?geo_lat),',',str(?geo_lon)), (if (bound(?isdate), year(?o_orig), (if (bound(?isnumber), round(?o_orig*100)/100, (if (bound(?iscoord), round(?o_orig*10000)/10000, ?o_orig))))))) as ?o)\
WHERE\
    {\
        {?s a aqr:ValidatedExceedence ; ?p ?o_orig FILTER(isLiteral(?o_orig))\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p ?o1 .\
            ?o1 rdfs:label ?o_orig\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqdd:broaderMetric ?o2 .\
            ?o2 rdfs:label ?o_orig\
            FILTER (str(?p1) in ('http://reference.eionet.europa.eu/aq/ontology/aggregationType'))\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/aggregationType_reportingmetric> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:relevantEmissions ?o2 .\
            ?o2 aqr:stationClassification ?o3 .\
            ?o3 skos:notation ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_stationtype> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:areaClassification ?o2 .\
            ?o2 skos:notation ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/station')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/station_stationarea> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:analyticalTechnique ?o2 .\
            ?o2 rdfs:label ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/procedure')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/procedure_analyticaltechnique> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:measurementType ?o2 .\
            ?o2 rdfs:label ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/procedure')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/procedure_measurementtype> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:inletHeight ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/sample')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/sample_inletHeight> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:kerbDistance ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/sample')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/sample_kerbdistance> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:zone ?o2 .\
            ?o2 aqr:inspireId ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zone> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:zone ?o2 .\
            ?o2 rdfs:label ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneLabel> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:zone ?o2 .\
            ?o2 aqr:zoneType ?o3.\
            ?o3 rdfs:label ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneType> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:zone ?o2 .\
            ?o2 dcterms:spatial ?o3.\
            ?o3 rdfs:label ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneCountryLabel> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:inspireId ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_samplingPoint> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:inspireId ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/sample')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/sample_sample> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:inspireId ?o_orig\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/procedure')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/procedure_procedure> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) in ('http://reference.eionet.europa.eu/aq/ontology/beginPosition'))\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/beginPosition_year> as ?p) WHERE { } }\
            { SELECT ('true' as ?isdate) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/airqualityValue')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/airqualityValue_aqvalue> as ?p) WHERE { } }\
            { SELECT ('true' as ?isnumber) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/datacapturePct')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/datacapturePct_datacapture> as ?p) WHERE { } }\
            { SELECT ('true' as ?isnumber) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/station_lat')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/station_lat_stationlatitude> as ?p) WHERE { } }\
            { SELECT ('true' as ?iscoord) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/station_lon')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/station_lon_stationlongitude> as ?p) WHERE { } }\
            { SELECT ('true' as ?iscoord) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/station')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/station_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/aggregationType')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/aggregationType_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqdd:broaderMetric ?o_orig .\
            FILTER (str(?p1) in ('http://reference.eionet.europa.eu/aq/ontology/aggregationType'))\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/aggregationType_reportingmetric_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/pollutant')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/pollutant_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:relevantEmissions ?o2 .\
            ?o2 aqr:stationClassification ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_stationtype_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:areaClassification ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/station')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/station_stationarea_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:analyticalTechnique ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/procedure')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/procedure_analyticaltechnique_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:measurementType ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/procedure')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/procedure_measurementtype_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/sample')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/sample_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:zone ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zone_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:zone ?o2 .\
            ?o2 aqr:zoneType ?o_orig.\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneType_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o1 .\
            ?o1 aqr:zone ?o2 .\
            ?o2 dcterms:spatial ?o_orig.\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_zoneCountryLabel_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/samplingPoint')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/samplingPoint_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence ; ?p1 ?o_orig .\
            FILTER (str(?p1) = 'http://reference.eionet.europa.eu/aq/ontology/procedure')\
            { SELECT (<http://reference.eionet.europa.eu/aq/ontology/procedure_link> as ?p) WHERE { } }\
        }\
        UNION\
        {?s a aqr:ValidatedExceedence;\
              aqr:station_lon ?geo_lon;\
              aqr:station_lat ?geo_lat\
              { SELECT (<http://reference.eionet.europa.eu/aq/ontology/station_geo_pos> as ?p) WHERE { }}\
              { SELECT ('true' as ?isgeo) WHERE { } }\
        }\
        <filter>\
}";

var filterTemplate_ = "FILTER (?s in (<slist>))"

var filterLength = 100000;

var sQuery_ = "SELECT ?s WHERE { ?s a <http://reference.eionet.europa.eu/aq/ontology/ValidatedExceedence>} order by ?s"


var queryTemplate = 

"PREFIX rod: <http://rod.eionet.europa.eu/schema.rdf#>\
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\
PREFIX dcterms: <http://purl.org/dc/terms/>\
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\
PREFIX cr: <http://cr.eionet.europa.eu/ontologies/contreg.rdf#>\
PREFIX aq: <http://rdfdata.eionet.europa.eu/airquality/ontology/>\
PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/>\
PREFIX aqdd: <http://dd.eionet.europa.eu/property/>\
\
SELECT DISTINCT \
 \
(?relemiURI as ?_id) \
?Country  \
(?locURI as ?Country_link) \
?Namespace  \
(YEAR(?beginPosition) as ?ReportingYear)  \
?NetworkId  \
(?NetURI as ?NetworkId_link) \
?NetworkName \
?StationId \
(?staURI as ?StationId_link)  \
?EUStationCode  \
?StationName \
?SamplingPointId \
(?SamplingPointURI as ?SamplingPointId_link) \
(bif:either(?AQD > 0,'YES','NO') as ?UsedForAQD)  \
?AggregationType \
(?AggregationTypeURI as ?AggregationType_link) \
?ReportingMetric \
(?ReportingMetricURI as ?ReportingMetric_link) \
?ObjectiveType \
(?ObjectiveTypeURI as ?ObjectiveType_link) \
?ProtectionTarget \
(?ProtectionTargetURI as ?ProtectionTarget_link) \
?Pollutant \
(?PollutantURI as ?Pollutant_link)  \
(ROUND(?AQvalue * 100)/100.0 AS ?AQvalue) \
(?statsURI as ?AQvalue_link) \
?ExceedanceThreshold \
(?thresURI as ?ExceedanceThreshold_link) \
(bif:either(substr(str(?Unit),1,56) = 'http://dd.eionet.europa.eu/vocabulary/uom/concentration/',REPLACE(str(?Unit),'http://dd.eionet.europa.eu/vocabulary/uom/concentration/',''),REPLACE(str(?Unit),'http://dd.eionet.europa.eu/vocabulary/uom/statistics/','')) as ?Unit) \
(ROUND(xsd:decimal(?DataCoverage) * 100)/100.0 AS ?DataCoverage) \
?VerificationFlag \
(?verURI as ?VerificationFlag_link) \
?StationType \
(?typeURI as ?StationType_link) \
?StationArea \
(?areaURI as ?StationArea_link) \
ROUND(?StationLat * 10000)/10000.0 AS ?StationLatitude  \
ROUND(?StationLong * 10000)/10000.0 AS ?StationLongitude \
?Zone \
(?ZoneURI as ?Zone_link) \
?ZoneLabel \
?ZoneType \
(?zonetypeURI as ?ZoneType_link) \
 \
WHERE { \
 \
{ \
SELECT DISTINCT * \
 \
 WHERE { \
 \
  ?SamplingPointURI a aqr:SamplingPoint ; \
            dcterms:source ?source; \
            aqr:inspireNamespace ?Namespace . \
 \
 ?envelope rod:hasFile ?source . \
 ?envelope rod:locality ?locURI . \
 ?locURI rdfs:label ?Country . \
 \
OPTIONAL{?SamplingPointURI aqr:zone ?ZoneURI} . \
OPTIONAL{?ZoneURI aqr:zoneCode ?Zone} . \
OPTIONAL{?ZoneURI rdfs:label ?ZoneLabel} . \
OPTIONAL{?ZoneURI aqr:zoneType ?zonetypeURI} . \
OPTIONAL{?zonetypeURI rdfs:label ?ZoneType} . \
 \
?SamplingPointURI aqr:belongsTo ?NetURI . \
?SamplingPointURI aqr:broader ?staURI . \
?SamplingPointURI aqr:inspireId ?SamplingPointId . \
 \
OPTIONAL{?SamplingPointURI aqr:relevantEmissions ?relemiURI} . \
OPTIONAL{?relemiURI aqr:stationClassification ?typeURI} . \
OPTIONAL{?typeURI rdfs:label ?StationType} . \
 \
OPTIONAL{?NetURI aqr:inspireId ?NetworkId} . \
OPTIONAL{?NetURI aqr:name ?NetworkName} . \
 \
?staURI aqr:inspireId ?StationId . \
?staURI aqr:EUStationCode ?EUStationCode . \
?staURI aqr:name ?StationName . \
?staURI aqr:areaClassification ?areaURI . \
?areaURI rdfs:label ?StationArea . \
 \
OPTIONAL{?SamplingPointURI aqr:usedAQD ?AQD} . \
 \
?statsURI aqr:samplingPoint ?SamplingPointURI . \
 \
?statsURI aqr:pollutant ?PollutantURI . \
?PollutantURI skos:notation ?Pollutant . \
 \
?statsURI aqr:airqualityValue ?AQvalue . \
?statsURI aqr:datacoveragePct ?DataCoverage . \
 \
?statsURI aqr:observationVerification ?verURI . \
?verURI rdfs:label ?VerificationFlag . \
 \
?statsURI aqr:aggregationType ?AggregationTypeURI . \
OPTIONAL{?AggregationTypeURI rdfs:label ?AggregationType} . \
OPTIONAL{?AggregationTypeURI aqdd:broaderMetric ?ReportingMetricURI} . \
 \
?statsURI aqr:beginPosition ?beginPosition . \
?statsURI aqr:station_lat ?StationLat . \
?statsURI aqr:station_lon ?StationLong . \
 \
OPTIONAL{?statsURI aqr:unit ?Unit} . \
 \
?thresURI aqdd:relatedPollutant ?PollutantURI . \
?thresURI aqdd:aggregationProcess ?AggregationTypeURI . \
?thresURI aqdd:hasReportingMetric ?ReportingMetricURI . \
?thresURI aqdd:hasObjectiveType ?ObjectiveTypeURI . \
?thresURI aqdd:hasProtectionTarget ?ProtectionTargetURI . \
?thresURI aqdd:exceedanceThreshold ?ExceedanceThreshold . \
 \
?ReportingMetricURI rdfs:label ?ReportingMetric . \
?ObjectiveTypeURI rdfs:label ?ObjectiveType . \
?ProtectionTargetURI rdfs:label ?ProtectionTarget . \
 \
FILTER regex(?Namespace,'ES.BDCA.AQD') . \
FILTER regex(?PollutantURI, 'http://dd.eionet.europa.eu/vocabulary/aq/pollutant/5$') . \
 \
}} \
 \
}  \
ORDER BY  \
?Country  \
ASC(?PollutantURI)  \
DESC(?AggregationType) ASC(?beginPosition)";

var filterTemplate = "FILTER (?areURI in (<slist>))";

var sQuery = 
"PREFIX aqr: <http://reference.eionet.europa.eu/aq/ontology/> \
SELECT ?areURI as ?s \
WHERE { \
    ?areURI a aqr:AssessmentRegime \
} \
ORDER BY ?areURI";


var normProp = {};
for (var i = 0; i < fields.length; i++){
    normProp[fields[i]] = fields[i].split("/")[fields[i].split("/").length - 1];
}

module.exports = {
    'endpoint': endpoint,
    'queryType': queryType,
    'normProp': normProp,
    'sQuery': sQuery,
    'filterLength': filterLength,
    'filterTemplate': filterTemplate,
    'queryTemplate': queryTemplate
};
